source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ExamplePod_Example', :exclusive => true do
  pod "ExamplePod", :path => "../"
end

target 'ExamplePod_Tests', :exclusive => true do
  pod "ExamplePod", :path => "../"

  
end
